---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qemu-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 16Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: qemu
  labels:
    name: qemu
spec:
  containers:
  - name: qemu
    image: qemux/qemu-arm
    env:
    - name: BOOT
      value: "https://dl-cdn.alpinelinux.org/alpine/v3.19/releases/aarch64/alpine-virt-3.19.1-aarch64.iso"
    - name: RAM_SIZE
      value: "1G"
    - name: CPU_CORES
      value: "1"
    - name: DISK_SIZE
      value: "16G"
    ports:
    - containerPort: 8006
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
      privileged: true
    volumeMounts:
    - mountPath: /storage
      name: storage
    - mountPath: /dev/kvm
      name: dev-kvm
    - mountPath: /dev/net/tun
      name: dev-tun
  terminationGracePeriodSeconds: 120
  volumes:
  - name: storage
    persistentVolumeClaim:
      claimName: qemu-pvc
  - hostPath:
      path: /dev/kvm
    name: dev-kvm
  - hostPath:
      path: /dev/net/tun
      type: CharDevice
    name: dev-tun
---
apiVersion: v1
kind: Service
metadata:
  name: qemu
spec:
  ports:
  - name: tcp-8006
    port: 8006
  selector:
    name: qemu
  type: NodePort
