name: "\U0001F6A8 Technical issue"
description: 
title: "[Issue]: "
labels: ["issue"]
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if a solution already exists for your issue.
      options:
      - label: I have searched the existing issues
        required: true
  - type: input
    id: cpu
    attributes:
      label: Machine specifications
      description: The processor and RAM amount in your machine.
      placeholder: e.g. Raspberry Pi 5 / 8 GB 
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: Operating system
      description: The distribution and kernel version (as shown by `uname -a`).
      placeholder: e.g. Ubuntu 24.04 / Kernel 6.8.0-22-generic
    validations:
      required: true
  - type: input
    id: docker
    attributes:
      label: Docker version
      description: The version of the Docker engine (as shown by `docker -v`).
      placeholder: e.g. 26.0.1
    validations:
      required: true
  - type: textarea
    id: summary
    attributes:
      label: Description
      description: A clear and concise description of your issue.
    validations:
      required: true
  - type: textarea
    id: compose
    attributes:
      label: Docker compose
      description: The compose file (or otherwise the `docker run` command used).
    validations:
      required: true
  - type: textarea
    id: log
    attributes:
      label: Docker log
      description: The logfile of the container (as shown by `docker logs qemu`).
    validations:
      required: true
  - type: textarea
    id: screenshot
    attributes:
      label: Screenshots (optional)
      description: Screenshots that might help to make the problem more clear.
    validations:
      required: false
